language: node_js
node_js:
- '8'
cache: yarn
script:
- npm run ci
deploy:
  provider: npm
  skip_cleanup: true
  email: rplan-ci@actano.de
  on:
    tags: true
    repo: actano/rplan-couchbase
    node: '8'
  api_key:
    secure: DDICH9BevyJI9watVJZzAmPBw9hvgRoswYk0Eqc7aYJ7PcMma6mEk0DJNfEy9/3tB9ocN57lQdhsbErwX5ywOniAAi9EaHnJoOd2jU0mbD06un128mN0HSPwzWybhiG+ZqmnEPkVMThJvh40csr9+5ODiyCRMj57uvCm91txBN3udDStmwTZu5IjuizmsxteiR2ntm5BkQwYwqJOs8NDwRM1Fo2e61Kjn+PfNJcJV/X4xPNSuPChvE158JPqooWmLbhYengRtCRedfYU7cTCescEBvhN3+frSVGUFU0zR2Xuyb80AZot04vtwSOD1pI8GCzmHTtR4vnBfVhG7endiMwvLI++l6IcC9XcNs0ciK+atFk8P6KFrmJNQ+oWHE3N4hJa11Uv2u7jui1MuauKpu8C1q5y0ir5VgoT8LX/HxSwqqii1i3vATDo4HqYyIwQq8qFN81R3YBiB0ZHYjJqTbA8LmOXGNzcbOcFSgM7RDzdtVlPEASezT8Nr2PMcx4oXx3dMKI/asCmZ+YfQN8jLN/R8J9WZB61RBDe34dKUKtvZtp5DDml8/741402UMiJ/rxku56+06D0gOiD9zXY7PBg0qHZ/er6ALuLlbKP6SXmE/NHBE3oUzdSegceFZ2t0Fl87vo1y3JVtvK7TSmrv544eiL4sg0Hsqrap8v7sLU=
